// <auto-generated />
namespace examenNa.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class CamposAbligatoriosClientePlanCobertura : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CamposAbligatoriosClientePlanCobertura));
        
        string IMigrationMetadata.Id
        {
            get { return "201912201734454_CamposAbligatoriosCliente,Plan,Cobertura"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
